



* Blueberry Oatmeal Bake
Makes 10 servings / 325 calories
Prep time: 5 minutes • Cook time: 40 to 45 minutes

** Ingredients
½ teaspoon coconut oil
1 (13.5-ounce) can lite coconut milk
1 flax egg (1 tbs flax meal + 2½ tbs water)
¼ cup maple syrup
1 teaspoon pure vanilla extract
½ teaspoon ground cinnamon
¼ teaspoon salt
3¼ cups old-fashioned rolled oats
1 cup fresh or frozen blueberries

** Instructions

1. Preheat the oven to 375°F. Grease an 8-by-8-inch glass baking
dish with the coconut oil.

2. In a large bowl, make flax egg. Then add the coconut milk,
maple syrup, vanilla, cinnamon, and salt and whisk to combine.

3. To the large bowl, add the oats and blueberries and mix well
with a spoon to combine.

4. Spread the oatmeal mixture in the prepared baking dish and
bake for 30 to 40 minutes, or until the top is a light, toasty
brown. Set on a wire rack to cool.


* Lentil Dal with Brown Rice
Makes 6 servings / 461 calories
Prep time: 15 minutes • Cook time: 30 minutes

** Ingredients
2 cup Basic Brown Rice
4 tablespoons coconut oil
2 medium yellow onion, diced
4 garlic cloves, minced
2-inch piece fresh ginger, grated
4 teaspoons ground coriander
2 teaspoon ground cumin
2 teaspoon ground turmeric
8 cups water, plus 4 tablespoons
4 golden potatoes, diced
2 carrot, cut into thin rounds
1 cup brown lentils
2 teaspoon salt
1 teaspoon freshly ground black pepper

** Instructions

1. Make the brown rice.
   
2. While the rice cooks, in a large pot, heat the coconut oil over
medium heat. Add the onion and cook for 3 to 4 minutes. or
until softened. Add the garlic, ginger, coriander, cumin, and
turmeric and cook for 1 minute, stirring frequently, until the
spices are incorporated and fragrant. Add 1 tablespoon of
water and gently scrape the bottom of the pot where spices
and vegetables are sticking.

3. Add the potatoes and carrot and cook for 2 minutes, stiring
frequently to coat the vegetables with spices. If the vegetables
are sticking to the bottom of the pan, add another tablesooon
of water and scrape up the stuck bits.

4. Add the lentils, salt, pepper, and remaining 4 cups of water.
Increase the heat to medium-high and bring the mixture
to a boil, then reduce the heat to low and simmer for 20 to
25 minutes, or until the lentils are soft and the potatoes are
cooked through.
