



* Coconut Oatmeal
Makes 10 servings, 430 calories (sans berries)/~150g/serving
Prep time: 5 minutes • Cook time: 40 to 45 minutes

** Ingredients
28g / 2 tbs coconut oil
2 (13.5-ounce) can coconut milk
20 g / 2 tbs flax meal 
180g / 1/2 cup maple syrup
10g / 2 teaspoon pure vanilla extract
1 teaspoon ground cinnamon
½ teaspoon salt
560g / 7 cups old-fashioned rolled oats
10 serv of berries

** Instructions

1. Mix, oats last. Add berries before eating.



* Lentil Dal with Brown Rice
Makes 6 servings / 461 calories
Prep time: 15 minutes • Cook time: 30 minutes

** Ingredients
2 cup Basic Brown Rice
4 tablespoons coconut oil
2 medium yellow onion, diced
4 garlic cloves, minced
2-inch piece fresh ginger, grated
4 teaspoons ground coriander
2 teaspoon ground cumin
2 teaspoon ground turmeric
8 cups water, plus 4 tablespoons
4 golden potatoes, diced
2 carrot, cut into thin rounds
1 cup brown lentils
2 teaspoon salt
1 teaspoon freshly ground black pepper

** Instructions

1. Make the brown rice.
   
2. While the rice cooks, in a large pot, heat the coconut oil over
medium heat. Add the onion and cook for 3 to 4 minutes. or
until softened. Add the garlic, ginger, coriander, cumin, and
turmeric and cook for 1 minute, stirring frequently, until the
spices are incorporated and fragrant. Add 1 tablespoon of
water and gently scrape the bottom of the pot where spices
and vegetables are sticking.

3. Add the potatoes and carrot and cook for 2 minutes, stiring
frequently to coat the vegetables with spices. If the vegetables
are sticking to the bottom of the pan, add another tablesooon
of water and scrape up the stuck bits.

4. Add the lentils, salt, pepper, and remaining 4 cups of water.
Increase the heat to medium-high and bring the mixture
to a boil, then reduce the heat to low and simmer for 20 to
25 minutes, or until the lentils are soft and the potatoes are
cooked through.


* Lasagna
10 servings / 488 (???) calories
Prep time: 30 minutes • Cook time: 45 minutes

** Ingredients
24 whole wheat lasagna noodles
1 (15-ounce) container ricotta cheese
1 large egg
½ cup chopped fresh parsley
1 teaspoon dried basil
1 teaspoon dried oregano
½ teaspoon freshly
ground black pepper
2 cups shredded mozzarella cheese, divided
2 teaspoons olive oil
½ medium yellow onion, diced
1 (8-ounce) container mushrooms, sliced
2 garlic cloves, minced 1½ (25-ounce) jars
marinara sauce, divided
2 cups baby spinach, roughly chopped


** Instructions
1. Preheat the oven to 350°F. Bring a large pot of water to a boil
over high heat.
2. Add the lasagna noodles to the boiling water and cook for
8 to 10 minutes, until soft. Drain and gently lay the 12 lasagna
noodles out flat on a large piece of parchment paper to cool
Use tongs or gloves to avoid burning your fingers.
3. In a medium bowl, combine the ricotta, egg, parsley, basil,
oregano, pepper, and ¾ cup of mozzarella. Stir until combined
and set it aside.
4. In a saucepan, heat the oil over medium-high heat until warn
Add the onion and sauté for 2 to 3 minutes, or until soft Add
the mushrooms and garlic and cook for 3 to 4 minutes more,
until the mushrooms are soft. Add the marinara sauce and
spinach. Simmer for 6 minutes and remove from the heat
5. To assemble the lasagna roll-ups, spread ¼ cup of the
ricotta mixture evenly onto each lasagna noodle, leaving a
¼-inch border on each end. On top of the ricotta, soread
2 tablespoons of sauce and 1 tablespoon of mozzarela
Carefully roll up each noodle with the ricotta, sauce, and
mozzarella inside.
6. Coat the bottom of a 9-by-12-inch glass baking dish wit
½ cup of sauce. Place each lasagna roll, seam-side don
on the sauce in the pan. Top the lasagna rolls with the
remaining 2½ cups of sauce and the remaining K 09
of mozzarella.
48

