

* Pantry Staples
How many for each/year?

** flours
*** whole wheat flour
pantry 3 months
*** all purpose flour
pantry 3 months

** oils
olive
sesame
coconut
avocado (?; pricy)

** grains
rolled oats
quinoa
brown rice
white rice
whole wheat pasta

** legumes
green lentils
red lentils
northern beans
black beans
pinto beans
kidney beans
chickpeas

** nuts
almonds
walnuts
pecans
cashews

** canned
tomatoes
tomato paste
coconut milk


* Coconut Oatmeal
Makes 10 servings, 430 calories (sans berries)/~150g/serving
Prep time: 5 minutes • Cook time: 40 to 45 minutes

** Ingredients
28g / 2 tbs coconut oil
2 (13.5-ounce) can coconut milk
20 g / 2 tbs flax meal 
180g / 1/2 cup maple syrup
10g / 2 teaspoon pure vanilla extract
1 teaspoon ground cinnamon
½ teaspoon salt
560g / 7 cups old-fashioned rolled oats
10 serv of berries

** Instructions

1. Mix, oats last. Add berries before eating.



* Lentil Dal with Brown Rice
Makes 6 servings / 461 calories
Prep time: 15 minutes • Cook time: 30 minutes

** Ingredients
2 cup Basic Brown Rice
4 tablespoons coconut oil
2 medium yellow onion, diced
4 garlic cloves, minced
2-inch piece fresh ginger, grated
4 teaspoons ground coriander
2 teaspoon ground cumin
2 teaspoon ground turmeric
8 cups water, plus 4 tablespoons
4 golden potatoes, diced
2 carrot, cut into thin rounds
1 cup brown lentils
2 teaspoon salt
1 teaspoon freshly ground black pepper

** Instructions

1. Make the brown rice.
   
2. While the rice cooks, in a large pot, heat the coconut oil over
medium heat. Add the onion and cook for 3 to 4 minutes. or
until softened. Add the garlic, ginger, coriander, cumin, and
turmeric and cook for 1 minute, stirring frequently, until the
spices are incorporated and fragrant. Add 1 tablespoon of
water and gently scrape the bottom of the pot where spices
and vegetables are sticking.

3. Add the potatoes and carrot and cook for 2 minutes, stiring
frequently to coat the vegetables with spices. If the vegetables
are sticking to the bottom of the pan, add another tablesooon
of water and scrape up the stuck bits.

4. Add the lentils, salt, pepper, and remaining 4 cups of water.
Increase the heat to medium-high and bring the mixture
to a boil, then reduce the heat to low and simmer for 20 to
25 minutes, or until the lentils are soft and the potatoes are
cooked through.


* Lasagna
10 servings / 488 (???) calories
Prep time: 30 minutes • Cook time: 45 minutes

** Ingredients
24 whole wheat lasagna noodles
800g Veggie Mince

*** Ragu

4 tbs Olive Oil, for frying
2 Red Onion, finely sliced
6 cloves Garlic, minced
8 sticks Celery, finely sliced
2 medium eggplant, cubed
2 zucchini, cubed
4 cans Chopped Tomatoes
6 tbs Tomato Puree
1 heaped tbs Mixed Herb
4 tbs Balsamic Vinegar
4 tsp Sea Salt
2 tsp Cracked Black Pepper


*** Béchamel Sauce 
1 cup Butter
1 cup Flour 

8 cups Soy Milk/Oat Milk
2 Onion, peeled & cut into 8
2 Bay leaf
2 Pinch Nutmeg
2 tsp Sea Salt
2 tsp Black Pepper Corns
2 cup Grated Vegan Cheese (optional)
4 tbs Nutritional Yeast (optional)

* Veggie Mince 
10 servings (hopefully)

** Ingredients
2 cauliflower, crumbled
16 oz mushrooms
2 cups walnuts

** Instructions
 Cut and dehydrate cauliflower and mushrooms at 160 for 3ish hours

 Process the cauliflower and mushrooms seperately from the walnuts before mixing







 
* Weekly Eats
** 02/14/22
*** Shopping
4 medium yellow onion, diced
2 Red Onion, finely sliced
4 garlic cloves, minced
2-inch piece fresh ginger, grated
4 golden potatoes, diced
2 carrot, cut into thin rounds
10 servings kale
10 whole wheat wraps
2 cauliflower, crumbled
16 oz mushrooms
2 cups walnuts
8 sticks Celery, finely sliced
2 medium eggplant, cubed
2 zucchini, cubed
4 cans Chopped Tomatoes
6 tbs Tomato Puree
1 heaped tbs Mixed Herb
4 tbs Balsamic Vinegar
4 tsp Sea Salt
2 tsp Cracked Black Pepper
1 cup Butter
whole wheat Flour 

2 Bay leaf
2 Pinch Nutmeg
2 tsp Sea Salt
2 cup Grated Vegan Cheese (optional)
4 tbs Nutritional Yeast (optional)
